const demoUsers = [
  {
    id: "11111111-1111-4111-8111-111111111111",
    fullName: "Budi Santoso",
    email: "warga@email.com",
    password: "password",
    role: "citizen",
  },
  {
    id: "22222222-2222-4222-8222-222222222222",
    fullName: "Admin DPU",
    email: "admin@dpu.go.id",
    password: "password",
    role: "admin",
  },
  {
    id: "33333333-3333-4333-8333-333333333333",
    fullName: "Siti Rahma",
    email: "siti@email.com",
    password: "password",
    role: "citizen",
  },
  {
    id: "44444444-4444-4444-8444-444444444444",
    fullName: "Nadia Putri",
    email: "nadia@email.com",
    password: "password",
    role: "citizen",
  },
];

const demoReports = [
  {
    id: "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaa1",
    referenceCode: "RPT-2024-0512",
    reporterId: demoUsers[0].id,
    categorySlug: "pothole",
    title: "Jalan Berlubang di Jl. Ahmad Yani",
    description:
      "Lubang cukup besar di tengah jalan, berbahaya untuk motor terutama saat malam hari.",
    latitude: -6.1817,
    longitude: 106.8663,
    address: "Jl. Ahmad Yani No. 45, Kec. Cempaka Putih",
    district: "Jakarta Pusat",
    status: "new",
    isVerified: false,
    upvoteCount: 32,
    createdAt: "2024-05-12T09:24:00.000Z",
    updatedAt: "2024-05-12T09:24:00.000Z",
    image: {
      id: "bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbb1",
      imageUrl: "/images/report-pothole.svg",
      storageKey: "reports/RPT-2024-0512/main.svg",
      alt: "Permukaan jalan berlubang dan rusak",
    },
    logs: [
      {
        id: "cccccccc-cccc-4ccc-8ccc-ccccccccccc1",
        nextStatus: "new",
        note: "Laporan diterima dari warga.",
        updatedBy: null,
        createdAt: "2024-05-12T09:24:00.000Z",
      },
    ],
  },
  {
    id: "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaa2",
    referenceCode: "RPT-2024-0489",
    reporterId: demoUsers[0].id,
    categorySlug: "streetlight",
    title: "Lampu Jalan Mati di Jl. Kenanga",
    description:
      "Tiga lampu penerangan mati berurutan sehingga area menjadi gelap dan rawan.",
    latitude: -6.2389,
    longitude: 106.8121,
    address: "Jl. Kenanga No. 12, Jakarta Selatan",
    district: "Jakarta Selatan",
    status: "verified",
    isVerified: true,
    upvoteCount: 18,
    createdAt: "2024-05-02T20:11:00.000Z",
    updatedAt: "2024-05-03T08:00:00.000Z",
    image: {
      id: "bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbb2",
      imageUrl: "/images/report-streetlight.svg",
      storageKey: "reports/RPT-2024-0489/main.svg",
      alt: "Jalan kota saat malam hari",
    },
    logs: [
      {
        id: "cccccccc-cccc-4ccc-8ccc-ccccccccccc2",
        nextStatus: "new",
        note: "Laporan diterima dari warga.",
        updatedBy: null,
        createdAt: "2024-05-02T20:11:00.000Z",
      },
      {
        id: "cccccccc-cccc-4ccc-8ccc-ccccccccccc3",
        previousStatus: "new",
        nextStatus: "verified",
        note: "Lokasi dan foto laporan sudah diverifikasi.",
        updatedBy: demoUsers[1].id,
        createdAt: "2024-05-03T08:00:00.000Z",
      },
    ],
  },
  {
    id: "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaa3",
    referenceCode: "RPT-2024-0410",
    reporterId: demoUsers[2].id,
    categorySlug: "puddle",
    title: "Genangan Air di Jl. Melati",
    description: "Genangan muncul setelah hujan dan menutup sebagian lajur kiri.",
    latitude: -6.2196,
    longitude: 106.8996,
    address: "Jl. Melati Raya, Jakarta Timur",
    district: "Jakarta Timur",
    status: "in_progress",
    isVerified: true,
    upvoteCount: 41,
    createdAt: "2024-04-28T16:45:00.000Z",
    updatedAt: "2024-05-01T10:30:00.000Z",
    image: {
      id: "bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbb3",
      imageUrl: "/images/report-puddle.svg",
      storageKey: "reports/RPT-2024-0410/main.svg",
      alt: "Jalan basah setelah hujan",
    },
    logs: [
      {
        id: "cccccccc-cccc-4ccc-8ccc-ccccccccccc4",
        nextStatus: "new",
        note: "Laporan diterima dari warga.",
        updatedBy: null,
        createdAt: "2024-04-28T16:45:00.000Z",
      },
      {
        id: "cccccccc-cccc-4ccc-8ccc-ccccccccccc5",
        previousStatus: "verified",
        nextStatus: "in_progress",
        note: "Tim lapangan dijadwalkan mengecek saluran air.",
        updatedBy: demoUsers[1].id,
        createdAt: "2024-05-01T10:30:00.000Z",
      },
    ],
  },
  {
    id: "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaa4",
    referenceCode: "RPT-2024-0322",
    reporterId: demoUsers[0].id,
    categorySlug: "flood",
    title: "Banjir Lokal di Perumahan Cendana",
    description: "Air masuk ke bahu jalan dan kendaraan kecil harus memutar.",
    latitude: -6.2615,
    longitude: 106.9732,
    address: "Perumahan Cendana, Bekasi",
    district: "Bekasi",
    status: "resolved",
    isVerified: true,
    upvoteCount: 57,
    createdAt: "2024-04-20T08:30:00.000Z",
    updatedAt: "2024-04-24T15:10:00.000Z",
    image: {
      id: "bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbb4",
      imageUrl: "/images/report-flood.svg",
      storageKey: "reports/RPT-2024-0322/main.svg",
      alt: "Banjir lokal di jalan lingkungan",
    },
    logs: [
      {
        id: "cccccccc-cccc-4ccc-8ccc-ccccccccccc6",
        nextStatus: "new",
        note: "Laporan diterima dari warga.",
        updatedBy: null,
        createdAt: "2024-04-20T08:30:00.000Z",
      },
      {
        id: "cccccccc-cccc-4ccc-8ccc-ccccccccccc7",
        previousStatus: "in_progress",
        nextStatus: "resolved",
        note: "Saluran air dibersihkan dan jalan sudah dapat dilewati.",
        updatedBy: demoUsers[1].id,
        createdAt: "2024-04-24T15:10:00.000Z",
      },
    ],
  },
  {
    id: "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaa5",
    referenceCode: "RPT-2024-0508",
    reporterId: demoUsers[3].id,
    categorySlug: "pothole",
    title: "Lubang di Jl. Kebon Raya",
    description: "Lubang memanjang dekat belokan dan belum ada penanda.",
    latitude: -6.1699,
    longitude: 106.7591,
    address: "Jl. Kebon Raya, Jakarta Barat",
    district: "Jakarta Barat",
    status: "resolved",
    isVerified: true,
    upvoteCount: 25,
    createdAt: "2024-05-08T07:19:00.000Z",
    updatedAt: "2024-05-10T11:00:00.000Z",
    image: {
      id: "bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbb5",
      imageUrl: "/images/report-road.svg",
      storageKey: "reports/RPT-2024-0508/main.svg",
      alt: "Permukaan jalan perkotaan",
    },
    logs: [
      {
        id: "cccccccc-cccc-4ccc-8ccc-ccccccccccc8",
        nextStatus: "resolved",
        note: "Perbaikan selesai.",
        updatedBy: demoUsers[1].id,
        createdAt: "2024-05-10T11:00:00.000Z",
      },
    ],
  },
];

module.exports = {
  demoUsers,
  demoReports,
};
